### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by YangBai1109** [fiy2W/BUS-GAN#1]

**Comment by YangBai1109** [comment]
hello ,When will the code be made public? I have read your paper. want to reproduce your code.

**Comment by fiy2W** [comment]
The code is on the computer in the school but I have to stay at home because of the Novel Coronavirus. Maybe one or two months needed to wait.

**Comment by YangBai1109** [comment]
> The code is on the computer in the school but I have to stay at home because of the Novel Coronavirus. Maybe one or two months needed to wait.

Ok, I hope you are safe. Is it convenient to ask you if i have any questions .
