### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by crie12138** [fiy2W/BUS-GAN#2]
hello, I am wondering about the csv in the config.py, I have read the paper, but I still do not know what the three csvs stand for. Also, how many pictures are there in "image","seg" ,respectively? And why those are the same folders for the test set?

**Comment by fiy2W** [comment]
The filename of the original BUS image (image) and mask (seg) are the same. But the two kinds of files are in different folders. So I use a csv file to collect all the files and load them at once. The train set and test set are divided in the code, if you wonder, you can also use different csv for train and test sets.

And the csv is simple, only a list of filenames with(out) labels as follows.

list_with_label.csv
filename,label
name1,0
name2,0
name3,1
name4,1

list_without_label.csv
filename
name1
name2
name3
name4

**Comment by crie12138** [comment]
Take the experiment in your paper as an example, you set the 2000+800+163 original pictures in the image folder, and 100 masks in the seg folder.  "list_0.csv" includes 100 pictures with their masks, for example, every row is denoted as "0001,0001"... "0100,0100". "list_1.csv" includes 1900 pictures without masks, "list.csv" include the 800+160 pictures, both csvs only have filename in each row. Is that true? As your answer said, lable in the "list_with_lable" is just 0 and 1,or the lable is as I've described. If there is any problem, please tell me.

**Comment by fiy2W** [comment]
Sorry, my explanation is confusing. The label I mentioned is not for segmentation but something like benign or malignant of the tumor and it is not used in this experiment. It would be work that all the lists are denoted as "list_without_label.csv".

**Comment by crie12138** [comment]
I still want to know how many data are there in each csv? If you can provide the three CSVs mentioned in the code(list_0.csv, list_1.csv, list.csv), maybe I can find some clearer answers. My email address is shown on my home page. Thanks a lot!

**Comment by fiy2W** [comment]
"list_0.csv" includes 100 picture names. "list_1.csv" includes 1900 picture names, "list.csv" includes 800 picture names. In each list, there is only one column for image names.
In addition, the public test set (163 images) is not involved in this code.

**Comment by crie12138** [comment]
well, I see, thank you!
