### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by wangman131237** [fiy2W/BUS-GAN#4]
您好，我配置的是tensorflow1.8.0版本，tensorlayer1.10.0版本，但是pycharm上面报错说tensorlayer的版本太高，很多函数弃用了，错误如下：WARNING:root:Lossy conversion from float64 to uint8. Range [-1.0, 1.0]. Convert image to uint8 prior to saving to suppress this warning.WARNING:root:Lossy conversion from bool to uint8. Range [False, True]. Convert image to uint8 prior to saving to suppress this warning。所以我想问t一下您tensorlayer的具体适配版本是多少呢？

**Comment by fiy2W** [comment]
您好，这个警告是说将float64转换为uint8时会有精度损失，并不是报错，可以忽略。因为我现在已经转为用pytorch了，对于tensorflow和tensorlayer的问题已经不太记得了。
